"""LLM-powered quiz generator for dynamic assessment creation.

Replaces hardcoded quiz scaffolding with dynamic generation from
text content via an Ollama agent client.
"""

import json
import uuid
from dataclasses import dataclass

from cognitive_agent.agent_client import CognitiveAgentClient


class QuizGenerationError(Exception):
    """Raised when the LLM fails to produce valid quiz JSON."""


@dataclass
class GeneratedQuizItem:
    """A single quiz item generated by the LLM.

    Attributes:
        quiz_item_id: Auto-generated unique identifier.
        question: The question text.
        category: Question category (always "short_answer").
        difficulty: Difficulty level ("easy", "medium", or "hard").
        required_keywords: Core concepts needed for a correct answer.
    """

    quiz_item_id: str
    question: str
    category: str
    difficulty: str
    required_keywords: list[str]


class QuizGeneratorService:
    """Generates quiz items from text content using an LLM.

    Takes a CognitiveAgentClient (typically OllamaAgentClient) as a
    dependency and produces structured quiz data from source text.

    Args:
        client: The cognitive agent client for LLM calls.
    """

    def __init__(self, client: CognitiveAgentClient) -> None:
        self._client = client

    def generate_quiz_from_text(
        self,
        topic: str,
        text_content: str,
        num_questions: int = 3,
    ) -> list[GeneratedQuizItem]:
        """Generate quiz items from text content via LLM.

        Args:
            topic: The topic being quizzed.
            text_content: The source text to generate questions from.
            num_questions: Number of questions to generate (default: 3).

        Returns:
            List of GeneratedQuizItem instances.

        Raises:
            QuizGenerationError: If the LLM response cannot be parsed
                as valid quiz JSON.
        """
        prompt = self._build_prompt(topic, text_content, num_questions)
        raw_response = self._client.generate_raw(prompt)
        return self._parse_response(raw_response)

    def _build_prompt(
        self,
        topic: str,
        text_content: str,
        num_questions: int,
    ) -> str:
        """Construct the LLM prompt for quiz generation.

        Args:
            topic: The topic being quizzed.
            text_content: The source text to generate questions from.
            num_questions: Number of questions to generate.

        Returns:
            The formatted prompt string.
        """
        return (
            "You are an expert educator creating a quiz assessment.\n\n"
            f"TOPIC: {topic}\n\n"
            f"SOURCE TEXT:\n{text_content}\n\n"
            f"TASK: Generate exactly {num_questions} quiz questions based "
            "on the source text above.\n\n"
            "REQUIREMENTS:\n"
            "- Each question must test understanding of core concepts\n"
            "- Include a mix of difficulty levels (easy, medium, hard)\n"
            "- required_keywords must contain 2-4 core concepts needed "
            "for a correct answer\n"
            "- All questions must be short_answer category\n\n"
            "OUTPUT FORMAT: Return ONLY a JSON array. No conversational "
            "filler. No explanations. No markdown.\n\n"
            "JSON SCHEMA:\n"
            "[\n"
            "  {\n"
            '    "quiz_item_id": "auto-generated-uuid",\n'
            '    "question": "string",\n'
            '    "category": "short_answer",\n'
            '    "difficulty": "easy|medium|hard",\n'
            '    "required_keywords": ["keyword1", "keyword2"]\n'
            "  }\n"
            "]\n\n"
            "CRITICAL: Return ONLY the raw JSON array. Nothing else."
        )

    def _parse_response(self, raw_response: str) -> list[GeneratedQuizItem]:
        """Parse the LLM response into GeneratedQuizItem instances.

        Args:
            raw_response: The raw text response from the LLM.

        Returns:
            List of parsed GeneratedQuizItem instances.

        Raises:
            QuizGenerationError: If the response cannot be parsed.
        """
        cleaned = raw_response.strip()

        if cleaned.startswith("```"):
            lines = cleaned.split("\n")
            end = -1 if lines[-1].strip() == "```" else None
            cleaned = "\n".join(lines[1:end])
            cleaned = cleaned.strip()

        try:
            data = json.loads(cleaned)
        except json.JSONDecodeError as exc:
            raise QuizGenerationError(f"Failed to parse LLM response as JSON: {exc}") from exc

        if not isinstance(data, list):
            raise QuizGenerationError(f"Expected JSON array, got {type(data).__name__}")

        items: list[GeneratedQuizItem] = []
        for entry in data:
            if not isinstance(entry, dict):
                raise QuizGenerationError(f"Expected dict in array, got {type(entry).__name__}")

            item_id = entry.get("quiz_item_id", "")
            if not item_id:
                item_id = f"quiz-{uuid.uuid4().hex[:12]}"

            items.append(
                GeneratedQuizItem(
                    quiz_item_id=item_id,
                    question=str(entry.get("question", "")),
                    category=str(entry.get("category", "short_answer")),
                    difficulty=str(entry.get("difficulty", "medium")),
                    required_keywords=list(entry.get("required_keywords", [])),
                )
            )

        return items
