"""Pydantic models for the Cognitive Agent service.

Defines the strict schema that the LLM must produce for lesson sections.
This is the trust boundary between LLM output and trusted data.
"""

from typing import Self

from pydantic import BaseModel, Field, field_validator


class LessonSectionGenerationError(Exception):
    """Raised when LLM output fails schema validation or is otherwise untrustworthy.

    Callers must handle this — it is NOT optional to catch, and it must never be
    silently swallowed into a fabricated fallback section.
    """

    pass


class LessonSectionDraft(BaseModel):
    """Strict schema for a lesson section generated by the LLM.

    This model defines the exact structure and validation rules that the LLM
    must follow. Any deviation results in a LessonSectionGenerationError.
    """

    section_title: str = Field(min_length=1, max_length=200, description="Title of the lesson section")
    body: str = Field(min_length=50, max_length=4000, description="Main content of the lesson section")
    source_indices: list[int] = Field(
        description=(
            "Indices into the grounding_chunks list passed in, identifying which "
            "chunks this section actually draws from. MUST reference at least "
            "one valid index — a section with zero sources is a validation "
            "failure, not a warning."
        )
    )

    @field_validator("source_indices")
    @classmethod
    def must_have_at_least_one_source(cls, v: list[int]) -> Self:
        """Validate that the section cites at least one source."""
        if len(v) == 0:
            raise ValueError("section must cite at least one source_index")
        return v

    @field_validator("source_indices")
    @classmethod
    def validate_indices_are_non_negative(cls, v: list[int]) -> Self:
        """Validate that all source indices are non-negative."""
        for idx in v:
            if idx < 0:
                raise ValueError(f"source_indices must be non-negative, got {idx}")
        return v
